### ISSUE TITLE
Aggregate various coverage-summary files into one report

### ISSUE THREAD

**Issue by vhoyer** [jacobbowdoin/comment-test-coverage#12]
```yaml
    - name: Comment Test Coverage
      uses: AthleticNet/comment-test-coverage@master
      with:
        title: Test Coverage
        token: ${{ secrets.GITHUB_TOKEN }}
        path:
          - packages/pkg1/coverage/coverage-summary.json
          - packages/pkg2/coverage/coverage-summary.json
          - packages/pkg3/coverage/coverage-summary.json
```

or even better

```yaml
    - name: Comment Test Coverage
      uses: AthleticNet/comment-test-coverage@master
      with:
        title: Test Coverage
        token: ${{ secrets.GITHUB_TOKEN }}
        path: packages/*/coverage/coverage-summary.json
```
